<a href="https://colab.research.google.com/github/dimasbayucmiiw/Kecerdasan-Buatan-2026/blob/main/jobsheet2ai.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Cek Tipe Data

In [ ]:
var = 123
print(type(var))

<class 'int'>


Tipe Data String

In [ ]:
a = '123'
b = '3.4'
c = "Data String"
print(type(c))

<class 'str'>


Tipe Data Numerik

In [ ]:
var1 = 345
var2 = 34.5
f1 = float(var1)
print(type(f1))
print(f1)

sum = var1 + var2
print(sum)

var3 = 12.3
var4 = 12.9
i1 = int(var2)
i2 = int(var3)
print(i1)
print(i2)

<class 'float'>
345.0
379.5
34
12


Tipe Data Boolean

In [ ]:
print(var1 == var2)
print(var1 < var2)
print(var1 > var2)
print(var1 != var2)

False
False
True
True


Tipe Data List

In [ ]:
list = ["belajar dasar python", 2023, 3.8, True]
print(list)
print(list[3])
print(list[1:3])
print(len(list))

['belajar dasar python', 2023, 3.8, True]
True
[2023, 3.8]
4


Mendapatkan nilai minimum dan maksimum

In [ ]:
x = min(5, 10, 25)
y = max(6, 12, 18)

Mendapatkan nilai absolut

In [ ]:
x = abs(-7.25)

Mendapatkan nilai pangkat

In [ ]:
import math
x = math.pow(4, 3)

Mendapatkan nilai akar

In [ ]:
import math
x = math.sqrt(64)

Mendapatkan nilai pembulatan

In [ ]:
import math
x = math.ceil(1.4)
y = math.floor(1.4)

Mendapatkan nilai konstanta (PI)

In [ ]:
import math
x = math.pi

Membuat matriks di python

In [ ]:
import numpy as np
A = np.array([[80, 30, 25],
              [50, 20, 10]])
B = np.array([[30, 60, 15],
              [10, 30, 30]])

hasil = A + B
print("Hasil =", A + B)

Hasil = [[110  90  40]
 [ 60  50  40]]


Melakukan operasi dot product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

hasil = np.dot(A, B)
print("Hasil =", np.dot(A,B))

Hasil = 2025


Melakukan operasi cross product

In [ ]:
import numpy as np
A = np.array([10, 20, 15])
B = np.array([16, 67, 35])

Hasil = np.cross(A, B)
print("Hasil =", np.cross(A,B))

Hasil = [-305 -110  350]


Hasil perkalian dalam matriks

In [ ]:
import numpy as np

A = np.array([[1, 2],
              [3, 4]])

B = np.array([[5, 6],
              [7, 8]])

C = np.array([[2, 0],
              [1, 2]])

hasil_AB = np.dot(A, B)
hasil_BC = np.dot(B, C)

print("A x B =\n", hasil_AB)
print("B x C =\n", hasil_BC)


A x B =
 [[19 22]
 [43 50]]
B x C =
 [[16 12]
 [22 16]]


Menghitung nilai faktorial

In [ ]:
import math

faktorial_6 = math.factorial(6)

hasil = math.factorial(8) / math.factorial(5)

print("6! =", faktorial_6)
print("8! / 5! =", hasil)

6! = 720
8! / 5! = 336.0


Hasil operasi vektor

In [ ]:
import numpy as np

A = np.array([5, 3, 7])
B = np.array([12, -3, 1])

panjang_A = np.linalg.norm(A)
panjang_B = np.linalg.norm(B)

dot_product = np.dot(A, B)
cross_product = np.cross(A, B)

print("Panjang vektor A =", panjang_A)
print("Panjang vektor B =", panjang_B)
print("A . B =", dot_product)
print("A x B =", cross_product)


Panjang vektor A = 9.1104335791443
Panjang vektor B = 12.409673645990857
A . B = 58
A x B = [ 24  79 -51]
